stories_project/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('story7_app.urls')),
    path('story8_app/', include('story8_app.urls')),
    path('story9_app/', include('story9_app.urls'))
]

story7_app/urls.py
from django.urls import path

from . import views

app_name = 'story7_app'

urlpatterns = [
    path('', views.home, name='home'),
]

story8_app/urls.py
from django.urls import path

from . import views

app_name = 'story8_app'

urlpatterns = [
    path('', views.home, name='home'),
    path('data/', views.data_function, name='data_function'),
]

story9_app/urls.py
from django.urls import path

from . import views

app_name = 'story9_app'

urlpatterns = [
    path("register/", views.register_function, name="register_function"),
    path("login/", views.login_function, name="login_function"),
    path("logout/", views.logout_function, name="logout_function"),
]

story7_app/models.py
from django.db import models

# Create your models here.

story8_app/models.py
from django.db import models

# Create your models here.

story9_app/models.py
from django.db import models

# Create your models here.

story9_app/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm

class RegistrationForm(UserCreationForm):
    username = forms.CharField(label="Username", widget=forms.TextInput(attrs={
        "class" : "form-control mb-3",
        "placeholder" : "Insert username"
    }))

    password1 = forms.CharField(label="Password", widget=forms.TextInput(attrs={
        "class" : "form-control mb-3",
        "placeholder" : "Insert Password",
        "type" : "password"
    }))

    password2 = forms.CharField(label="Confirm Password", widget=forms.TextInput(attrs={
        "class" : "form-control mb-3",
        "placeholder" : "Type the same Password",
        "type" : "password"
    }))

    class Meta:
        model = User
        fields = ["username", "password1", "password2"]

class LoginForm(AuthenticationForm):
    username = forms.CharField(label="Username", widget=forms.TextInput(attrs={
        "class" : "form-control mb-3",
        "placeholder" : "Insert Username"
    }))

    password = forms.CharField(label="Password", widget=forms.TextInput(attrs={
        "class" : "form-control mb-3",
        "placeholder" : "Insert Password",
        "type" : "password"
    }))

    class Meta:
        fields = "__all__"

story7_app/views.py
from django.shortcuts import render
from django.contrib.auth.models import User


def home(request):
    return render(request,
            'story7_app/home.html',
            {
                "is_story7_app" : True,
                "username" : request.user.username
            })

story8_app/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse
import requests
import json
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required


# Create your views here.
@login_required(login_url = "/story9_app/login")
def home(request):
    context = {
        "is_story8_app" : True,
        "username" : request.user.username
    }
    return render(request, "story8_app/home.html", context)

def data_function(request):
    arg = request.GET["q"]
    api_url = "https://www.googleapis.com/books/v1/volumes?q=" + arg
    response = requests.get(api_url)
    data = json.loads(response.content)
    return JsonResponse(data, safe=False)

story9_app/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth import login , logout, authenticate
from django.contrib.auth.models import User
from .forms import RegistrationForm, LoginForm, AuthenticationForm
from django.contrib import messages

def register_function(request):
    if request.user.is_authenticated:
        return redirect("story7_app:home")
    context = {
        "register" : RegistrationForm,
        "is_story9_app" : True,
    }

    if request.method == "POST":
        register = RegistrationForm(request.POST)
        if register.is_valid():
            register.save()
            new_user_account = authenticate(
                username = register.cleaned_data["username"],
                password = register.cleaned_data["password1"]
            )
            login(request, new_user_account)
            return redirect("story7_app:home")
        elif register.errors:
            for key in register.errors:
                messages.add_message(request, messages.WARNING, register.errors[key])
    return render(request, "story9_app/register.html", context)

def login_function(request):
    context = {
        "login" : LoginForm,
        "is_story9_app" : True,
    }
    if request.user.is_authenticated:
        return redirect("story7_app:home")
    
    if request.method == "POST":
        login_form = LoginForm(data = request.POST)
        if login_form.is_valid():
            user = login_form.get_user()
            login(request, user)
            return redirect("story7_app:home")
        elif login_form.errors:
            for key in login_form.errors:
                messages.add_message(request, messages.WARNING, login_form.errors[key])
    return render(request, "story9_app/login.html", context)

def logout_function(request):
    if request.user.is_authenticated:
        logout(request)
    return redirect("story7_app:home")

story7_app/templates/story7_app/home.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Story 7 Hadi</title>
{% endblock meta %}

{% block content %}
<div class="home-height">
  <section class="container-fluid">
    <div class="row">
      <div class="col-lg-6 col-sm-12 home-height d-flex justify-content-center align-items-center flex-column">
        <img class="w-75 bg-foto p-2 rounded-lg" src="{% static 'images/fotodiri.jpg'%}" alt="Foto diri">
        <div class="mt-3 bg-foto p-2 rounded-lg">
          Hi, my name's Hadi!
        </div>
      </div>
      <div class="col-lg-6 col-sm-12 home-height p-2 d-flex justify-content-center align-items-center flex-column">
        <div id="accordion">
          <h3 position="0" class="p-2 m-0 bg-foto">
            Siapa Saya?
            <span class="mx-1 float-right down" id="down">
              Down
            </span>
            <span class="mx-1 float-right up" id="up">
              Up
            </span>
          </h3>
          <p position="0" class="p-1 m-0 bg-content text-light">
            Mahasiswa tingkat dua Fasilkom UI. Saat ini sedang berusaha survive di semester 3 :')
          </p>
          <h3 position="1" class="p-2 m-0 bg-foto">
            Pengalaman dan Organisasi?
            <span class="mx-1 float-right down" id="down">
              Down
            </span>
            <span class="mx-1 float-right up" id="up">
              Up
            </span>
          </h3>
          <p position="1" class="p-1 m-0 bg-content text-light">
              Tim BFC Kemasyarakatan, 2017-2018
              <br>
              Pesta Rakyat Komputer, 2020
              <br>
              Staf Departemen Sosial Masyarakat FUKI Fasilkom UI, 2020-sekarang
              <br>
              Staf Akademis PMB Fasilkom UI 2020, 2020-sekarang
              <br>
              Staf Acara SIWAK-NG 2020
          </p>
          <h3 position="2" class="p-2 m-0 bg-foto">
            Prestasi?
            <span class="mx-1 float-right down" id="down">
              Down
            </span>
            <span class="mx-1 float-right up" id="up">
              Up
            </span>
          </h3>
          <p position="2" class="p-1 m-0 bg-content text-light">
            Soon enough. Let's go!
          </p>
          <h3 position="3" class="p-2 m-0 bg-foto">
            Contact Me!
            <span class="mx-1 float-right down" id="down">
              Down
            </span>
            <span class="mx-1 float-right up" id="up">
              Up
            </span>
          </h3>
          <p position="3" class="p-1 m-0 bg-content text-light">
            Kindly contact me in <span><a href="https://www.instagram.com/_hadipratama768/" class="text-dark">Instagram</a></span> atau <span><a href="https://line.me/ti/p/r3BU2vFGwr" class="text-dark">LINE</a></span>
          </p>
        </div>
      </div>
    </div>

  </section>
</div>
<script src="{% static 'js/script.js' %}"></script>
{% endblock content %}

story8_app/templates/story8_app/home.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Story 8 Hadi</title>
{% endblock meta %}

{% block content %}
<div class="jumbotron bg-jumbotron text-dark rounded-0 m-0">
    <div class="container">
        <h1 class="display-4">Pencarian Buku</h1>
        <p class="lead">Database provided by Google API</p>
        <hr class="my-4">
        <p>Silakan mencari buku yang Anda inginkan</p>
        <p class="lead">
        <div class="d-flex">
            <input type="text" id="book-form" class="form-control w-25 mr-1" placeholder="Book Title">
            <button class="btn btn-primary" id="find-btn" role="button">Search</button>
        </div>
        </p>
    </div>
</div>

<section class="bg-section text-light p-3 result-section">
    <h3 class="text-center p-0 m-0">Search Results (<span id="found-amount"></span>):</h3>
    
    <div class="d-flex flex-column align-items-center text-light" id="book-list">

        <h1 class="m-5 text-light">After clicking "search", the result will be displayed here</h1>

    </div>
</section>

<script src="{% static 'js/script_story8_app.js' %}"></script>
{% endblock content %}

story9_app/templates/story9_app/login.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Story 9 Hadi</title>
{% endblock meta %}

{% block content %}
<section class="d-flex justify-content-center align-items-center text-dark flex-column home-height">
    {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{message.tags}} alert-dismissible show fade" role="alert">
            {{ message }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
            </button>
        </div>
        {% endfor %}
    {% endif %}
    <form method="POST" action="{% url 'story9_app:login_function' %}" class="login-form bg-light rounded-lg d-flex flex-column justify-content-center p-4">
        <h3 class="text-center mb-3">Login</h3>
        {% csrf_token %}
        {{ login }}
        <button type="submit" id="btn_login" class="btn btn-primary">Login</button>
        <div class="card-footer">
            <div class="d-flex justify-content-center links">
                Don't have an account? =><a class="text-dark"href="{% url 'story9_app:register_function' %}"> Create a new one here</a>
            </div>
        </div>
    </form>
</section>
{% endblock %}

story9_app/templates/story9_app/register.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Story 9 Hadi</title>
{% endblock meta %}

{% block content %}
<section class="d-flex justify-content-center align-items-center text-dark flex-column home-height">
    {% if messages %}
        {% for message in messages %}
          <div class="alert alert-{{message.tags}} alert-dismissible show fade" role="alert">
            {{ message }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
        {% endfor %}
      {% endif %}
    <form method="POST" action="{% url 'story9_app:register_function' %}" class="login-form bg-light rounded-lg d-flex flex-column justify-content-center p-4">
        <h3 class="text-center mb-3">Create an Account</h3>
        {% csrf_token %}
        {{ register }}
        <button type="submit" id="btn_register" class="btn btn-primary">Register</button>
        <div class="card-footer">
            <div class="d-flex justify-content-center links">
                Already have an account? =><a class="text-dark"href="{% url 'story9_app:login_function' %}"> Login here</a>
            </div>
        </div>
    </form>
</section>

{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">

  <!-- Enable jQuery -->
  <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

  {% block meta %}
  {% endblock meta %}
</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-navbar">
    {% if is_story7_app == True %}
    <a class="navbar-brand text-light" href="#">Story 7 Hadi</a>
    {% elif is_story8_app == True %}
    <a class="navbar-brand text-light" href="#">Story 8 Hadi</a>
    {% elif is_story9_app == True %}
    <a class="navbar-brand text-light" href="#">Story 9 Hadi</a>
    {% endif %}
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        {% if is_story9_app != True %}
          <a class="nav-item nav-link active text-light" href="#"> Home <span class="sr-only">(current)</span></a>
        {% else %}
          <a class="nav-item nav-link text-light" href="{% url 'story7_app:home' %}"> Story 7 </a>
          <a class="nav-item nav-link text-light" href="{% url 'story8_app:home' %}"> Story 8 </a>
        {% endif %}
        {% if is_story7_app == True %}
          <a class="nav-item nav-link text-light" href="{% url 'story8_app:home' %}"> Story 8 </a>
        {% elif is_story8_app == True %}
          <a class="nav-item nav-link text-light" href="{% url 'story7_app:home' %}"> Story 7 </a>
        {% endif %}
        {% if request.user.is_authenticated %}
          <a class="nav-item nav-link text-light"> Welcome, {{ username }} </a>
          <a class="nav-item nav-link text-light" href="{% url 'story9_app:logout_function' %}"> Logout </a>
        {% elif not request.user.is_authenticated %}
          <a class="nav-item nav-link text-light"  href="{% url 'story9_app:register_function' %}"> Register </a>
          <a class="nav-item nav-link text-light"  href="{% url 'story9_app:login_function' %}"> Login </a>
        {% endif %}
      </div>
    </div>
  </nav>
  {% block content %}
  {% endblock content %}
  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>

</html>